version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  load_database:
    build:
      context: .
      dockerfile: docker/load_database/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - load_database
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./Sistema/frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
