# Generated by Django 5.0.6 on 2024-05-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActividadCliente",
            fields=[],
            options={
                "db_table": "actividad_cliente",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ActividadCobertura",
            fields=[],
            options={
                "db_table": "actividad_cobertura",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FranquiciaCobertura",
            fields=[],
            options={
                "db_table": "franquicia_cobertura",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OfertaCobertura",
            fields=[],
            options={
                "db_table": "oferta_cobertura",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SublimiteCobertura",
            fields=[],
            options={
                "db_table": "sublimite_cobertura",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CatalogoActividades",
            fields=[
                ("id_actividad", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_actividad", models.CharField(max_length=100, unique=True)),
                ("agravada_flag", models.BooleanField()),
            ],
            options={
                "db_table": "catalogo_actividades",
            },
        ),
        migrations.CreateModel(
            name="CatalogoCoberturas",
            fields=[
                ("id_cobertura", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_cobertura", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "catalogo_coberturas",
            },
        ),
        migrations.CreateModel(
            name="CatalogoFranquicias",
            fields=[
                ("id_franquicia", models.AutoField(primary_key=True, serialize=False)),
                ("franquicia", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "catalogo_franquicias",
            },
        ),
        migrations.CreateModel(
            name="CatalogoProvincias",
            fields=[
                ("id_provincia", models.AutoField(primary_key=True, serialize=False)),
                ("provincia", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "catalogo_provincias",
            },
        ),
        migrations.CreateModel(
            name="CatalogoSublimites",
            fields=[
                ("id_sublimite", models.AutoField(primary_key=True, serialize=False)),
                ("sublimite", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "catalogo_sublimites",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_cliente",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                (
                    "nombre_cliente",
                    models.CharField(default="None", max_length=250, unique=True),
                ),
                ("volumen_facturacion", models.FloatField()),
                (
                    "id_provincia",
                    models.ForeignKey(
                        db_column="id_provincia",
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_interfaz.catalogoprovincias",
                    ),
                ),
            ],
            options={
                "db_table": "clientes",
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                ("id_oferta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "suma_asegurada",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "limite_anualidad",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("semaforo", models.IntegerField(blank=True, null=True)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        db_column="id_cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_interfaz.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "ofertas",
            },
        ),
    ]
